### ISSUE TITLE
Centos container doesnt start

### ISSUE THREAD

**Issue by huegelc** [tpokorra/lxc-scripts#18]
Hi,
the centos container doesn´ t start on ubuntu 14.04:
this is the output of lxc-start -n <containername>

Failed to install release agent, ignoring: File exists
Cannot add dependency job for unit display-manager.service, ignoring: Unit display-manager.service failed to load: No such file or directory.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Listening on Delayed Shutdown Socket.
[  OK  ] Reached target Encrypted Volumes.
[  OK  ] Listening on Journal Socket.
         Mounting POSIX Message Queue File System...
         Starting Create static device nodes in /dev...
         Mounting FUSE Control File System...
         Mounting Huge Pages File System...
         Starting Journal Service...
[  OK  ] Started Journal Service.
         Mounting Debug File System...
[  OK  ] Reached target Swap.
         Starting Remount Root and Kernel File Systems...
[  OK  ] Created slice Root Slice.
[  OK  ] Created slice User and Session Slice.
[  OK  ] Created slice System Slice.
[  OK  ] Reached target Slices.

**Comment by tpokorra** [comment]
did you try to run https://github.com/tpokorra/lxc-scripts/blob/master/initLXC.sh again?
after an upgrade of the lxc package, that initLXC.sh needs to be run again

**Comment by huegelc** [comment]
Thank you, that solved the problem. Great
